# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
# fr:
#   languageCode: fr
# #  contentDir: content/fr
#   title: Page Personnel
# #  params:
# #    description: Site description in Chinese...
#  menu:
#    main:
#     - name: Acceuil
#       url: '#about'
#       weight: 10
#     - name: Publications
#       url: '#featured'
#       weight: 20
#     - name: Présentations
#       url: '#talks'
#       weight: 30
#     - name: Enseignements
#       url: '#courses'
#       weight: 40
#     - name: Contact
#       url: '#contact'
#       weight: 50

# zh:
#   languageCode: zh-Hans
#  contentDir: content/zh
#   title: 个人主页
# #  params:
# #    description: Site description in Chinese...
#  menu:
#    main:
#     - name: 主页
#       url: '#about'
#       weight: 10
